# Generated by Django 6.0.3 on 2026-04-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
